### ISSUE TITLE
mdslw not ignoring frontmatter

### ISSUE THREAD

**Issue by skadic** [razziel89/mdslw#10]
Hello,
it seems that `mdslw` formats frontmatter as well in some cases. An example:
```md
---
item1: hello
item2:
- my
- list
---
```
`mdslw` should not change this, but when run, it yields:
```md
---
item1:
hello item2:
- my
- list
---
```

**Comment by razziel89** [comment]
Thank you very much for reporting this issue as well as an example and a fix! You are correct, the formatter must not modify the frontmatter. I'll take a look at the suggested fix as soon as time permits.

**Comment by razziel89** [comment]
FYI @Skadic: I'll release version 0.7.0 in a few minutes, which should fix the issue. All feedback is welcome.
