### ISSUE TITLE
Convert `--features` into something more permanent

### ISSUE THREAD

**Issue by razziel89** [razziel89/mdslw#16]
At the moment, the `--features` flag serves as a bit of a dumping ground for new functionality that may or may not be useful. Those `--features` that are unused or not useful should be removed while those `--features` that are use and useful should be converted into something more permanent. They could be converted into their own command line flags, for example.

If you are a user of `mdslw` and find specific features useful, please comment on this issue, naming those useful `--features`. At the moment, more or less all `--features` are up for removal.

**Comment by bugabinga** [comment]
I vote for `retain-whitespace` :).
*cough* even though I am probably its only user *cough*

**Comment by razziel89** [comment]
The list of features has been reduced significantly. As there are only two left for now and one of them (`keep-spaces-in-links`) may even be removed, the `--features` flag can be kept as it is no longer a dumping ground. In case one feature has been removed, the other one will be turned into its own flag. Closing.
