### ISSUE TITLE
Make supporting new extensions easy

### ISSUE THREAD

**Issue by razziel89** [razziel89/mdslw#17]
~Many~ Some markdown extensions appear to work the following way:

- There is a single line that has a specific indentation, prefix character, or may simply contain text.
- The next line also has a specific indentation or a prefix character, but both values are different than for the previous line.
- At the same indentation level, arbitrary markdown content may follow. Not all extensions require indentation here, but requiring the same indentation level makes detection a lot easier and, thus, is likely a requirement that should be added.
- After an optional empty line, a line like the second one and everything following it may repeat.

In the example of [definition lists](https://michelf.ca/projects/php-markdown/extra/#def-list), the first line is simply unindented text while the second line may have some indentation and has a colon as a prefix character.

Such extensions could be supported by adding a generic struct that contains all that logic. It basically detects the markdown covered by the extension and extracts the _basic_ markdown contained within. Then, that extracted markdown, with a reduced maximum line width due to the indentation, can be formatted in the usual way.

**Comment by bugabinga** [comment]
What other extensions did you have in mind?

I am somewhat familiar with those listed here: <https://www.markdownguide.org/extended-syntax/#overview>.

However, at first glance, only definition list fit the scheme you described above, right?

**Comment by razziel89** [comment]
I had mostly admonitions as defined by the mkdocs for markdown theme ([docs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)) in mind. And since both admonitions and definition lists fit the bill, I came up with the idea.

**Comment by razziel89** [comment]
Admonitions can be supported by using non-breaking spaces (nbsp). That is, the starting markers such as `!!!` can be followed by an nbsp to prevent `mdslw` from adding a linebreak.

Definition lists can be supported in one of two ways. First, a user could use the feature `keep-linebreaks` to retain existing linebreaks globally. Instead, a user could prevent `mdslw` from removing a particular linebreak by prefixing it with an nbsp.

There are currently no other extensions used by users of `mdslw` that I know of. The current handling of nbsp makes it easy to prevent `mdslw` from modifying other special syntax. Thus, no additional functionality for detecting other features is needed at the moment. Users can always open a ticket if they need support for additional extensions and its implementation can be discussed.

Closing this ticket.
