### ISSUE TITLE
Provide more details about diff

### ISSUE THREAD

**Issue by razziel89** [razziel89/mdslw#19]
In case a file differs from the desired state, it could be useful to provide more information about the deviation. That way, `mdslw` could possibly even serve as a linter that could be hooked into a general purpose language server such as [efm-langserver](https://github.com/mattn/efm-langserver). The [similar](https://github.com/mitsuhiko/similar/tree/main) crate could be used to compute a diff. Since such a computation can be costly, it should only be done if explicitly requested.

**Comment by realJohnDoe** [comment]
I also noticed that some more output would be helpful regarding the specific file and line that caused a failure.

**Comment by razziel89** [comment]
The recently added `--report` flag lets users request varying degrees of detail about the actions done by `mdslw`. There is also a set of options that cause the computation of diffs. That information can be used to determine which changes `mdslw` has done or would do. Since `mdslw` is an auto-formatter and not a linter, that is considered sufficient. Closing.

Comments on this issue discussing the above are welcome.
